FROM jenkins/jenkins:lts-jdk17

USER root

# Mise à jour et installation de Maven + Docker
RUN apt-get update && \
    apt-get install -y maven docker.io && \
    rm -rf /var/lib/apt/lists/*

# Désactiver tout ce qui utilise le keyring (pour éviter l’erreur)
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dorg.jenkinsci.plugins.keyring=false"
ENV _JAVA_OPTIONS="-Djava.security.krb5.disableKeyTab=true"

# Retour à l'utilisateur jenkins
USER jenkins
