services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: docker-jenkins
    restart: unless-stopped
    privileged: true
    user: root
    security_opt:
      - no-new-privileges:false
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data: