pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo '📥 Clonage du projet Maven depuis GitHub...'
                git branch: 'test/alex', url: 'https://github.com/NWilliRex/Maintenance_Backend.git'
            }
        }

        stage('Build & Package') {
            steps {
                echo '⚙️ Compilation et packaging du projet Maven...'
                dir('Maintenance_Backend') {
                    sh 'mvn clean package -DskipTests=true'
                }
            }
        }

        stage('Test') {
            steps {
                echo '🧪 Exécution des tests unitaires et d’intégration...'
                dir('Maintenance_Backend') {
                    sh 'mvn test verify'
                }
            }
            post {
                always {
                    echo "📊 Publication des rapports de tests..."
                    junit '**/target/surefire-reports/*.xml'

                    // Publication du rapport JaCoCo
                    recordCoverage(
                        tools: [jacoco(pattern: '**/target/site/jacoco/jacoco.xml')],
                        sourceDirectories: [[path: 'src/main/java']]
                    )
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo '✅ Build réussie !'
            script {
                sh '''
                curl -H "Content-Type: application/json" \
                     -X POST \
                     -d '{"content": "✅ Build réussi sur Jenkins pour Maintenance_Backend ! 🎉"}' \
                     "https://discord.com/api/webhooks/1428945933177196716/DVFdGRP79ixTtzyrR1bdj8D_vkvMFn2TPj5Q7z8AD5MwOSFo26YPOccoYTb9loGyh_M2"
                '''
            }
        }
        failure {
            echo '❌ Échec de la build.'
            script {
                sh '''
                curl -H "Content-Type: application/json" \
                     -X POST \
                     -d '{"content": "❌ Build échoué sur Jenkins pour Maintenance_Backend 💥"}' \
                     "https://discord.com/api/webhooks/1428945933177196716/DVFdGRP79ixTtzyrR1bdj8D_vkvMFn2TPj5Q7z8AD5MwOSFo26YPOccoYTb9loGyh_M2"
                '''
            }
        }
    }
}