INSERT INTO person (fname, gender, age, role) VALUES
                                                  ('Schutt', 'MALE', 19, 'USER'),
                                                  ('Cauldfield', 'FEMALE', 20, 'USER'),
                                                  ('Caldecutt', 'OTHER', 21, 'USER'),
                                                  ('Perryman', 'MALE', 51, 'USER'),
                                                  ('Guerrieri', 'FEMALE', 90, 'USER'),
                                                  ('Drejer', 'FEMALE', 1, 'USER'),
                                                  ('Richley', 'MALE', 60, 'USER'),
                                                  ('Pharo', 'FEMALE', 12, 'USER'),
                                                  ('Lazenby', 'FEMALE', 23, 'USER'),
                                                  ('Whitehorne', 'OTHER', 45, 'USER'),
                                                  ('Fritschmann', 'FEMALE', 60, 'USER'),
                                                  ('Cato', 'MALE', 34, 'USER'),
                                                  ('Wickham', 'OTHER', 21, 'USER'),
                                                  ('Bondley', 'MALE', 60, 'USER'),
                                                  ('Shilito', 'FEMALE', 64, 'USER'),
                                                  ('Kneafsey', 'MALE', 32, 'USER'),
                                                  ('Cobden', 'FEMALE', 90, 'USER'),
                                                  ('Riddles', 'MALE', 43, 'USER'),
                                                  ('Mabbett', 'MALE', 3, 'USER'),
                                                  ('Santarelli', 'MALE', 5, 'USER'),
                                                  ('Hordle', 'FEMALE', 7, 'USER'),
                                                  ('Wannes', 'FEMALE', 42, 'USER'),
                                                  ('Pitherick', 'OTHER', 50, 'USER'),
                                                  ('Mortimer', 'FEMALE', 56, 'USER'),
                                                  ('Smallpiece', 'FEMALE', 12, 'USER'),
                                                  ('Houliston', 'FEMALE', 1, 'USER'),
                                                  ('Boast', 'MALE', 5, 'USER'),
                                                  ('Layson', 'FEMALE', 63, 'USER'),
                                                  ('Tomalin', 'MALE', 35, 'USER'),
                                                  ('Muldownie', 'MALE', 40, 'USER');

INSERT INTO serie (title, genre, nb_episodes, note) VALUES
                                                        ('Breaking Bad', 'Crime', 62, 9.5),
                                                        ('Stranger Things', 'Science-Fiction', 34, 8.7),
                                                        ('Game of Thrones', 'Fantasy', 73, 9.3),
                                                        ('The Witcher', 'Fantasy', 16, 8.2),
                                                        ('Friends', 'Comedy', 236, 8.9),
                                                        ('The Office', 'Comedy', 201, 8.8),
                                                        ('Dark', 'Science-Fiction', 26, 8.8),
                                                        ('Sherlock', 'Crime', 13, 9.1),
                                                        ('Money Heist', 'Crime', 41, 8.3),
                                                        ('Rick and Morty', 'Animation', 61, 9.0),
                                                        ('Avatar: The Last Airbender', 'Animation', 61, 9.2),
                                                        ('The Mandalorian', 'Science-Fiction', 16, 8.8),
                                                        ('The Crown', 'Drama', 60, 8.7),
                                                        ('Better Call Saul', 'Crime', 63, 8.8),
                                                        ('Black Mirror', 'Science-Fiction', 22, 8.8),
                                                        ('Vikings', 'Historical', 89, 8.5),
                                                        ('Narcos', 'Crime', 30, 8.8),
                                                        ('The Umbrella Academy', 'Superhero', 30, 8.0),
                                                        ('Stranger Things 2', 'Science-Fiction', 9, 8.5),
                                                        ('House of Cards', 'Drama', 73, 8.7);

INSERT INTO ratings (user_id, serie_id, user_rating) VALUES
                                                        (1, 1, 9.8),
                                                        (2, 1, 9.5),
                                                        (3, 1, 9.7),
                                                        (4, 1, 9.6),
                                                        (5, 1, 9.9),
                                                        (6, 1, 9.4),
                                                        (7, 2, 8.7),
                                                        (8, 2, 8.8),
                                                        (9, 2, 8.6),
                                                        (10, 2, 8.9),
                                                        (11, 2, 8.5),
                                                        (12, 3, 9.3),
                                                        (13, 3, 9.5),
                                                        (14, 3, 9.1),
                                                        (15, 3, 9.4),
                                                        (16, 3, 9.2),
                                                        (17, 4, 8.1),
                                                        (18, 4, 8.2),
                                                        (19, 4, 8.3),
                                                        (20, 4, 8.0),
                                                        (21, 4, 8.4),
                                                        (22, 5, 8.9),
                                                        (23, 5, 9.0),
                                                        (24, 5, 8.7),
                                                        (25, 5, 8.8),
                                                        (26, 5, 8.9),
                                                        (27, 6, 8.8),
                                                        (28, 6, 9.0),
                                                        (29, 6, 8.9),
                                                        (30, 6, 8.7),
                                                        (1, 6, 8.8),
                                                        (2, 7, 8.9),
                                                        (3, 7, 8.8),
                                                        (4, 7, 9.0),
                                                        (5, 7, 8.7),
                                                        (6, 7, 9.1),
                                                        (7, 8, 9.2),
                                                        (8, 8, 9.3),
                                                        (9, 8, 9.1),
                                                        (10, 8, 9.4),
                                                        (11, 8, 9.2),
                                                        (12, 9, 8.2),
                                                        (13, 9, 8.3),
                                                        (14, 9, 8.1),
                                                        (15, 9, 8.4),
                                                        (16, 9, 8.3),
                                                        (17, 10, 9.1),
                                                        (18, 10, 9.0),
                                                        (19, 10, 9.2),
                                                        (20, 10, 9.3),
                                                        (21, 10, 9.1),
                                                        (22, 11, 9.3),
                                                        (23, 11, 9.2),
                                                        (24, 11, 9.4),
                                                        (25, 11, 9.5),
                                                        (26, 11, 9.3),
                                                        (27, 12, 8.7),
                                                        (28, 12, 8.8),
                                                        (29, 12, 8.9),
                                                        (30, 12, 8.7),
                                                        (1, 12, 8.8),
                                                        (2, 13, 8.6),
                                                        (3, 13, 8.7),
                                                        (4, 13, 8.5),
                                                        (5, 13, 8.8),
                                                        (6, 13, 8.6),
                                                        (7, 14, 8.9),
                                                        (8, 14, 9.0),
                                                        (9, 14, 8.8),
                                                        (10, 14, 9.1),
                                                        (11, 14, 8.9),
                                                        (12, 15, 8.8),
                                                        (13, 15, 8.7),
                                                        (14, 15, 8.9),
                                                        (15, 15, 8.8),
                                                        (16, 15, 9.0),
                                                        (17, 16, 8.4),
                                                        (18, 16, 8.6),
                                                        (19, 16, 8.5),
                                                        (20, 16, 8.3),
                                                        (21, 16, 8.4),
                                                        (22, 17, 8.8),
                                                        (23, 17, 8.7),
                                                        (24, 17, 8.9),
                                                        (25, 17, 8.8),
                                                        (26, 17, 8.7),
                                                        (27, 18, 8.0),
                                                        (28, 18, 8.1),
                                                        (29, 18, 8.2),
                                                        (30, 18, 8.0),
                                                        (1, 18, 8.3),
                                                        (2, 19, 8.5),
                                                        (3, 19, 8.4),
                                                        (4, 19, 8.6),
                                                        (5, 19, 8.5),
                                                        (6, 19, 8.7),
                                                        (7, 20, 8.8),
                                                        (8, 20, 8.7),
                                                        (9, 20, 8.9),
                                                        (10, 20, 8.8),
                                                        (11, 20, 8.6);


